CHOOSE_OPTION = 0
FORWARD_POST_FOR_WATCH = 1
FORWARD_POST_FOR_SUB = 2
SET_PRICE_FOR_WATCH = 3
SET_PRICE_FOR_SUB = 4
SET_COUNT_OF_WATCH = 5
SET_COUNT_OF_SUB = 6
CONFIRM_WATCHS = 7
CONFIRM_SUB = 8

ADD_MONEY = 9
REMOVE_MONEY = 10
SHARE_INFO = 11
